## used in a prod vps only ##

version: "3.8"

# Services
services:
  ##############################################################################
  #                                   Frontend                                 #
  ##############################################################################
  frontend:
    container_name: frontend
    restart: always
    image: frontend-dev-fullstack-template #Adjust
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - fullstack-template #Adjust
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - CADDY_PROD_URL=${CADDY_PROD_URL}
      - CADDY_PROD_BACKEND_URL=${CADDY_PROD_BACKEND_URL}

  ##############################################################################
  #                                   Backend                                  #
  ##############################################################################
  backend:
    container_name: backend
    restart: always
    image: backend-dev-fullstack-template #Adjust
    networks:
      - fullstack-template #Adjust
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}

  ##############################################################################
  #                                   Database                                 #
  ##############################################################################
  db:
    container_name: db
    restart: always
    image: db-dev-fullstack-template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack-template #Adjust
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  #                                    Extra                                   #
  ##############################################################################

# Volumes
volumes:
  postgres_data:
  caddy_data:
  caddy_config:

# Networks
networks:
  fullstack-template: #Adjust
    driver: "bridge"
