## used in a prod vps only ##

version: "3.8"

# Services
services:
  ##############################################################################
  #                                   Frontend                                 #
  ##############################################################################
  frontend:
    container_name: frontend
    restart: always
    image: frontend-dev-fullstack-template
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - CADDY_PROD_URL=${CADDY_PROD_URL}
      - CADDY_PROD_BACKEND_URL=${CADDY_PROD_BACKEND_URL}

  ##############################################################################
  #                                   Backend                                  #
  ##############################################################################
  backend:
    container_name: backend
    restart: always
    image: backend-dev-fullstack-template
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network
    environment:
    - BACKEND_PORT=${BACKEND_PORT}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_PORT=${DATABASE_PORT}

  ##############################################################################
  #                                   Database                                 #
  ##############################################################################
  db:
    container_name: db
    restart: always
    image: db-dev-fullstack-template
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Adjust the volume name if using a different database
    networks:
      - shared-network
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"] # Adjust the healthcheck for different databases
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  #                                    Extra                                   #
  ##############################################################################

# Volumes
volumes:
  postgres_data: # Adjust the volume name if using a different database
  caddy_data:
  caddy_config:

# Networks
networks:
  shared-network: # Adjust the network name for project
    driver: "bridge"
