## used in a prod vps only ##

version: "3.8"

# Services
services:
  ##############################################################################
  #                                   Frontend                                 #
  ##############################################################################
  frontend:
    container_name: frontend
    restart: always
    image: ghcr.io/noorchasib/frontend-dev-fullstack-template:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network

  ##############################################################################
  #                                   Backend                                  #
  ##############################################################################
  backend:
    container_name: backend
    restart: always
    image: ghcr.io/noorchasib/backend-dev-fullstack-template:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network

  ##############################################################################
  #                                   Database                                 #
  ##############################################################################
  db:
    container_name: db
    restart: always
    image: ghcr.io/noorchasib/db-dev-fullstack-template:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data # Adjust the volume name if using a different database
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"] # Adjust the healthcheck for different databases
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  #                                    Extra                                   #
  ##############################################################################

# Volumes
volumes:
  postgres_data: # Adjust the volume name if using a different database
  caddy_data:
  caddy_config:

# Networks
networks:
  shared-network: # Adjust the network name for project
    driver: "bridge"
