version: "3.8"

# Services
services:
  ##############################################################################
  #                                   Frontend                                 #
  ##############################################################################
  frontend:
    container_name: frontend-${APP_NAME}
    tty: true
    restart: always
    build:
      context: ./src/frontend
      dockerfile: .docker/Dockerfile.prod
      args:
        - NODE_IMAGE=${NODE_IMAGE}
        - CADDY_IMAGE=${CADDY_IMAGE}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - backend
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network
    env_file: 
      - .env

  ##############################################################################
  #                                   Backend                                  #
  ##############################################################################
  backend:
    container_name: backend-${APP_NAME}
    tty: true
    restart: always
    build:
      context: ./src/backend
      dockerfile: .docker/Dockerfile.prod
      args:
      - NODE_IMAGE=${NODE_IMAGE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network
    env_file: 
      - .env

  ##############################################################################
  #                                   Database                                 #
  ##############################################################################
  db:
    container_name: db-${APP_NAME}
    image: ${DATABASE_IMAGE} # This will depend on setup and the images available
    restart: always
    environment: # Adapt these to match the database type you're using
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Adjust the volume name if using a different database
      - ./src/backend/db/schema:/docker-entrypoint-initdb.d # any .sql files in this folder will be executed on startup
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"] # Adjust the healthcheck for different databases
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  #                                    Extra                                   #
  ##############################################################################

# Volumes
volumes:
  postgres_data: # Adjust the volume name if using a different database
  caddy_data:
  caddy_config:

# Networks
networks:
  shared-network: # Adjust the network name for project
    driver: "bridge"
