version: "3.8"

# Services
services:
  ##############################################################################
  #                                   Frontend                                 #
  ##############################################################################
  frontend:
    container_name: frontend-${APP_NAME}
    restart: always
    build:
      context: ./src/frontend
      dockerfile: .docker/Dockerfile.prod
      args:
        - NODE_VERSION=${NODE_VERSION}
    depends_on:
      - backend
    networks:
      - shared-network

  ##############################################################################
  #                                   Backend                                  #
  ##############################################################################
  backend:
    container_name: backend-${APP_NAME}
    restart: always
    build:
      context: ./src/backend
      dockerfile: .docker/Dockerfile.prod
      args:
        - NODE_VERSION=${NODE_VERSION}
    depends_on:
      - db
    networks:
      - shared-network

  ##############################################################################
  #                                   Database                                 #
  ##############################################################################
  db:
    container_name: db-${APP_NAME}
    image: ${DATABASE_IMAGE} # This will depend on setup and the images available
    restart: always
    environment: # Adapt these to match the database type you're using
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Adjust the volume name if using a different database
      - ./src/backend/db/schema:/docker-entrypoint-initdb.d # any .sql files in this folder will be executed on startup
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"] # Adjust the healthcheck for different databases
      interval: 10s
      timeout: 5s
      retries: 5

  ##############################################################################
  #                                    Caddy                                   #
  ##############################################################################
  caddy:
    container_name: caddy-${APP_NAME}
    image: ${CADDY_IMAGE} # This will depend on setup and the images available
    restart: always
    ports:
      - 80:80 
      - 443:443
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - ./src/frontend/dist:/usr/src/app/frontend/dist
      - ./prod.Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    networks:
      - shared-network

  ##############################################################################
  #                                    Extra                                   #
  ##############################################################################

# Volumes
volumes:
  postgres_data: # Adjust the volume name if using a different database
  caddy_data:
  caddy_config:

# Networks
networks:
  shared-network: # Adjust the network name for project
