# Dockerfile for frontend service

# Accept build argument for Node version
ARG NODE_VERSION

# Use the Node.js image with the specified version
FROM node:${NODE_VERSION}

# Set the working directory inside the container
WORKDIR /usr/src/app/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the frontend code
COPY . .

# Build the frontend
RUN npm run build

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
