# Dockerfile for backend service

# Accept build argument for Node version
ARG NODE_VERSION

# Use the Node.js image with the specified version
FROM node:${NODE_VERSION}

# Set the working directory inside the container
WORKDIR /usr/src/app/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the backend code
COPY . .

# Build the backend
RUN npm run build

# Command to run the app
CMD [ "npm", "run", "start" ]
