name: Deploy - Dev DB - 2

on:
  workflow_dispatch:

env:
  IMAGE_NAME: db-dev-fullstack-template
  COMPOSE_FILE: compose.prod.yaml
  SOURCE_IMAGE: fullstack-template-db

jobs:
  build-and-deploy:
    name: Build and Deploy DB Image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DATABASE_IMAGE=${{ secrets.DATABASE_IMAGE }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env

      - name: Build DB Image using Docker Compose
        run: docker compose -f ${{ env.COMPOSE_FILE }} build db

      - name: Save the Docker Image
        run: docker save ${{ env.SOURCE_IMAGE }} > db.tar

      - name: Transfer the Image to the VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "db.tar"
          target: "/tmp"

      - name: Load the Image on the VPS and Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker load < /tmp/db.tar
            docker tag ${{ env.SOURCE_IMAGE }} ${{ env.IMAGE_NAME }}
            POSTGRES_DB=${{ secrets.DATABASE_NAME }} POSTGRES_USER=${{ secrets.DATABASE_USER }} POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }}docker compose up -d db

      - name: Cleanup
        run: rm -f db.tar
