name: Deploy - Dev Backend

on:
  workflow_dispatch:

env:
  USERNAME: noorchasib
  REGISTRY: ghcr.io
  IMAGE_NAME: noorchasib/backend-dev-fullstack-template:latest
  COMPOSE_FILE: compose.prod.yaml
  SOURCE_IMAGE: fullstack-template-backend

jobs:
  publish:
    name: Publish backend dev image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ env.USERNAME }} --password-stdin

      - name: Create .env file
        run: |
          echo "NODE_IMAGE=${{ secrets.NODE_IMAGE }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env

      - name: Build Backend Image using Docker Compose
        run: docker compose -f ${{ env.COMPOSE_FILE }} build backend

      - name: Tag the Built Image
        run: docker tag ${{ env.SOURCE_IMAGE }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish the Image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    needs: publish
    name: Deploy backend dev image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect and pull backend
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull backend && docker compose up -d backend && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
