name: Publish Frontend Dev Image

on:
  workflow_dispatch:

env:
  USERNAME: noorchasib
  REGISTRY: ghcr.io
  IMAGE_NAME: noorchasib/frontend-dev-fullstack-template:latest
  COMPOSE_FILE: compose.prod.yaml
  SOURCE_IMAGE: fullstack-template-frontend

jobs:
  publish:
    name: publish frontend dev image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ env.USERNAME }} --password-stdin

      - name: Create .env file
        run: |
          echo "NODE_IMAGE=${{ secrets.NODE_IMAGE }}" >> .env
          echo "CADDY_IMAGE=${{ secrets.CADDY_IMAGE }}" >> .env
          echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
          echo "CADDY_PROD_URL=${{ secrets.CADDY_PROD_URL }}" >> .env
          echo "CADDY_PROD_BACKEND_URL=${{ secrets.CADDY_PROD_BACKEND_URL }}" >> .env

      - name: Build Frontend Image using Docker Compose
        run: docker compose -f ${{ env.COMPOSE_FILE }} build frontend

      - name: Tag the Built Image
        run: docker tag ${{ env.SOURCE_IMAGE }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish the Image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
