name: Deploy - Dev DB

on:
  workflow_dispatch:

env:
  USERNAME: noorchasib
  REGISTRY: ghcr.io
  IMAGE_NAME: noorchasib/db-dev-fullstack-template:latest
  COMPOSE_FILE: compose.prod.yaml
  SOURCE_IMAGE: fullstack-template-db

jobs:
  publish:
    name: Publish db dev image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create .env file
        run: |
          echo "DATABASE_IMAGE=${{ secrets.DATABASE_IMAGE }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env

      - name: Build DB Image using Docker Compose
        run: docker compose -f ${{ env.COMPOSE_FILE }} build db

      - name: Tag the Built Image
        run: docker tag ${{ env.SOURCE_IMAGE }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish the Image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect and pull db
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull db && docker compose up -d db && exit"

      - name: Cleanup
        run: rm -rf ~/.ssh
