name: Publish Frontend Dev Image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/frontend-dev-fullstack-template:latest

jobs:
  publish:
    name: publish frontend dev image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish Frontend
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
